name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm run install:all

    - name: Build backend
      run: npm run build:backend

    - name: Build frontend
      run: npm run build:frontend
