-- liquibase formatted sql

-- changeset jan:1694936265955-1
CREATE TABLE "tickets" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "meetup_id" BIGINT NOT NULL, "user_id" BIGINT NOT NULL, "is_checked_in" BOOLEAN DEFAULT FALSE, "raffle_entries" INTEGER DEFAULT 0, "raffle_wins" INTEGER DEFAULT 0, CONSTRAINT "tickets_pkey" PRIMARY KEY ("id"));
CREATE TABLE "users" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" VARCHAR(100) NOT NULL, "first_name" VARCHAR(30), "last_name" VARCHAR(30), "nick_name" VARCHAR(30), "is_organizer" BOOLEAN DEFAULT FALSE, "is_admin" BOOLEAN DEFAULT FALSE, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
CREATE TABLE "meetups" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100) NOT NULL, "date" date NOT NULL, "organizer_ids" INT8[], "has_raffle" BOOLEAN DEFAULT FALSE, CONSTRAINT "meetups_pkey" PRIMARY KEY ("id"));
CREATE SEQUENCE  IF NOT EXISTS "meetups_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE  IF NOT EXISTS "tickets_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
CREATE SEQUENCE  IF NOT EXISTS "users_id_seq" AS bigint START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;
ALTER TABLE "users" ADD CONSTRAINT "email_unique" UNIQUE ("email");
ALTER TABLE "tickets" ADD CONSTRAINT "meetup_id_fkey" FOREIGN KEY ("meetup_id") REFERENCES "meetups" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tickets" ADD CONSTRAINT "user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- rollback ALTER TABLE "tickets" DROP CONSTRAINT "user_id_fkey";
-- rollback ALTER TABLE "tickets" DROP CONSTRAINT "meetup_id_fkey";
-- rollback ALTER TABLE "users" DROP CONSTRAINT "email_unique";
-- rollback DROP TABLE "meetups";
-- rollback DROP TABLE "users";
-- rollback DROP TABLE "tickets";


-- changeset jan:2
ALTER TABLE "meetups" ALTER COLUMN "id" TYPE BIGINT;
-- rollback ALTER TABLE "meetups" ALTER COLUMN "id" TYPE INTEGER;

-- changeset jan:3
ALTER TABLE "users" ADD COLUMN "password_hash" VARCHAR(60) NOT NULL;
-- rollback ALTER TABLE "users" DROP COLUMN "password_hash";

-- changeset jan:4
ALTER TABLE "meetups" ADD COLUMN "capacity" INT NOT NULL DEFAULT 0;
ALTER TABLE "meetups" ADD COLUMN "start_time" TIME WITHOUT TIME ZONE NOT NULL DEFAULT '00:00:00';
ALTER TABLE "meetups" ADD COLUMN "duration_hours" INT NOT NULL DEFAULT 0;
ALTER TABLE "meetups" ADD COLUMN "address_line_1" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE "meetups" ADD COLUMN "address_line_2" VARCHAR(255) DEFAULT '';
ALTER TABLE "meetups" ADD COLUMN "city" VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE "meetups" ADD COLUMN "state" VARCHAR(50) DEFAULT '';
ALTER TABLE "meetups" ADD COLUMN "country" VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE "meetups" ADD COLUMN "postal_code" VARCHAR(20) NOT NULL DEFAULT '';
-- rollback ALTER TABLE "meetups" DROP COLUMN "postal_code";
-- rollback ALTER TABLE "meetups" DROP COLUMN "country";
-- rollback ALTER TABLE "meetups" DROP COLUMN "state";
-- rollback ALTER TABLE "meetups" DROP COLUMN "city";
-- rollback ALTER TABLE "meetups" DROP COLUMN "address_line_2";
-- rollback ALTER TABLE "meetups" DROP COLUMN "address_line_1";
-- rollback ALTER TABLE "meetups" DROP COLUMN "duration_hours";
-- rollback ALTER TABLE "meetups" DROP COLUMN "start_time";
-- rollback ALTER TABLE "meetups" DROP COLUMN "capacity";

-- changeset jan:5
ALTER TABLE "meetups" DROP COLUMN "start_time";
ALTER TABLE "meetups" ALTER COLUMN "date" TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE "meetups" ADD COLUMN "utc_offset" INT NOT NULL DEFAULT 0;
-- rollback ALTER TABLE "meetups" DROP COLUMN "utc_offset";
-- rollback ALTER TABLE "meetups" ALTER COLUMN "date" TYPE DATE;
-- rollback ALTER TABLE "meetups" ADD COLUMN "start_time" TIME WITHOUT TIME ZONE NOT NULL DEFAULT '00:00:00';

-- changeset jan:6
ALTER TABLE "meetups" ADD COLUMN "image_url" VARCHAR(255) DEFAULT NULL;
-- rollback ALTER TABLE "meetups" DROP COLUMN "image_url";